default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  host: <%= ENV["PGHOST"] %>
  username: <%= ENV["PGUSER"] %>
  password: <%= ENV["PGPASS"] %>
  database: hellorok_development

test:
  <<: *default
  host: <%= ENV["PGHOST"] %>
  username: <%= ENV["PGUSER"] %>
  password: <%= ENV["PGPASS"] %>
  database: hellorok_test
  
production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
  username: <%= ENV["PGUSER"] %>
  password: <%= ENV["PGPASS"] %>
  database: hellorok_production
