apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2018-05-27T00:04:02Z
  labels:
    run: hellorok
  name: hellorok
  namespace: default
spec:
  clusterIP: 10.97.60.188
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30092
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    run: hellorok
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
